spring.application.name=event-ticket-booking
jwt.secret=mySuperSecretKeyForJwtAuthentication12345678901234567890
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/event_ticket_booking}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
